SO-98 Not Found Page
SacOverflow/CAMEL-Services pull request #8
Opened 2024-02-25 04:27 UTC by DGConn

Not Found page

2024-02-25 06:16 UTC, hashemJaber commented
was this resolved ?
was is the code error ?

2024-02-25 19:40 UTC, jvniorrr requested changes
Solid work. Working as expected. Just few changes to be incorporated. 

Will also need to rebase your current branch to be synced / aligned with the main branch.

2024-02-25 19:40 UTC, jvniorrr commented on src/app/not-found.tsx
> +const inter = Lexend_Giga({ subsets: ['latin'] });
unneeded import, can be removed

2024-02-25 19:40 UTC, jvniorrr commented on src/app/not-found.tsx
> +		<main className="flex min-h-screen flex-col items-center justify-between">
for this class name maybe use 
`<main className="flex min-h-screen flex-col items-center justify-between pt-5">`

2024-02-25 19:40 UTC, jvniorrr commented on src/app/not-found.tsx
> +			<section id="home-section">
`<section id="home-section flex flex-col items-center justify-between">`

2024-02-26 08:16 UTC, jvniorrr commented
Separate PR created, and merged..

2024-02-26 08:16 UTC, closed without merging